apiVersion: v1
kind: Namespace
metadata:
  name: {.NAMESPACE}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: {.NAMESPACE}
spec:
  replicas: 3
  selector:
    matchLabels:
      component: hello-world
  template:
    metadata:
      labels:
        component: hello-world
    spec:
      containers:
        - name: hello-world
          image: stanleywxc/hello-world:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 100m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: {.NAMESPACE}
  labels:
    name: hello-world-service
spec:
  type: NodePort
  selector:
    component: hello-world
  ports:
    - name: hello-world-port
      protocol: TCP
      port: 8080
      targetPort: 8080
